# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_default: system

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'Turf Västerbotten'
    description: 'Föreningen för turfare i regionen Västerbotten'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_search: true
    show_theme_chooser: true
    highlight_active_link: false

# Site footer
footer:
  copyright:
    notice: '© {year} Turf Västerbotten. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: '2 January 2006'
  time_format: '15:04'
  address_format: fi

# Site features
features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: github-dark
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
